contact_links:
  - name: Feature Request
    url: https://github.com/authz-pro/authz-pro/discussions/new
    about: Please request features here.
  - name: Translation Issues
    about: Please correct translation issues on Crowdin.
